# Generated by Django 5.2.3 on 2025-06-11 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('snack1', 'Snack1'), ('lunch', 'Lunch'), ('snack2', 'Snack2'), ('dinner', 'Dinner')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('estimated_time', models.CharField(help_text="Estimated time (e.g., '30 min', '1 hour')", max_length=50)),
                ('diners', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_unit', to='adminmenu.photo')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('activity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('objective', models.CharField(choices=[('lose', 'Lose weight'), ('keep', 'Keep weight'), ('gain', 'Gain weight')], default='keep', max_length=50)),
                ('family_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='adminmenu.familyunit')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='adminmenu.ingredientcategory')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_like', models.CharField(choices=[('prohibe', 'Prohibe'), ('gusta', 'Gusta')], max_length=10)),
                ('gravity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmenu.ingredient')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmenu.familymember')),
            ],
        ),
        migrations.AddField(
            model_name='familymember',
            name='ingredients',
            field=models.ManyToManyField(related_name='family_members', through='adminmenu.IngredientFamilyMember', to='adminmenu.ingredient'),
        ),
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('breakfast', 'Breakfast'), ('snack1', 'Snack1'), ('lunch', 'Lunch'), ('snack2', 'Snack2'), ('dinner', 'Dinner')], max_length=100)),
                ('plate_count', models.PositiveIntegerField(help_text='Cantidad de platos')),
                ('members', models.ManyToManyField(blank=True, related_name='foods', to='adminmenu.familymember')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='adminmenu.menu')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('frequency_per_week', models.IntegerField()),
                ('members', models.ManyToManyField(blank=True, related_name='activities', to='adminmenu.familymember')),
            ],
        ),
        migrations.CreateModel(
            name='MenuRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmenu.menu')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmenu.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='recipes',
            field=models.ManyToManyField(related_name='menus', through='adminmenu.MenuRecipe', to='adminmenu.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(related_name='recipes', to='adminmenu.recipecategory'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recipes', to='adminmenu.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='adminmenu.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('like_disklike', models.BooleanField(default=True)),
                ('save_create', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmenu.familymember')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmenu.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='members',
            field=models.ManyToManyField(related_name='recipes_with_relation', through='adminmenu.RecipeMember', to='adminmenu.familymember'),
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('severity', models.IntegerField()),
                ('ingredients', models.ManyToManyField(blank=True, related_name='restrictions', to='adminmenu.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='familymember',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='members', to='adminmenu.restriction'),
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('family_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='adminmenu.familyunit')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmenu.ingredient')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='adminmenu.shoppinglist')),
            ],
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='ingredients',
            field=models.ManyToManyField(related_name='shopping_lists', through='adminmenu.ShoppingListItem', to='adminmenu.ingredient'),
        ),
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeklyMealPlans', to='adminmenu.familymember')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='meal_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='adminmenu.weeklymealplan'),
        ),
    ]
